---
# GitLab build configuration

image: icpctools/golang:1.16

stages:
  - test
  - build

test:
  stage: test
  needs: []
  script:
    - go test -count=1 -v ./...

vet:
  stage: test
  needs: []
  script:
    - go vet ./...

staticcheck:
  stage: test
  needs: []
  script:
    - staticcheck ./...

format:
  stage: test
  needs: []
  script:
    - gofmt -d . > format.patch
    - DIFF=$(cat format.patch)
    - |
      if [[ $DIFF != "" ]];
      then
        cat format.patch;
        exit 1;
      fi

build:
  stage: build
  needs: [test, vet, staticcheck, format]
  script:
    - go build -o $BINARY
    - tar -cvzf contest-${GOOS}-${GOARCH}.tar.gz $BINARY
  parallel:
    matrix:
      - GOOS: windows
        GOARCH: [386, amd64]
        BINARY: contest.exe
      - GOOS: linux
        GOARCH: [386, amd64, arm64]
        BINARY: contest
      - GOOS: darwin
        GOARCH: [amd64, arm64]
        BINARY: contest
  artifacts:
    paths:
      - contest-${GOOS}-${GOARCH}.tar.gz
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
