name: Build
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        GOOS: [windows, linux, darwin]
        GOARCH: [amd64]
        include:
          - GOOS: windows
            GOARCH: 386
          - GOOS: linux
            GOARCH: 386
          - GOOS: linux
            GOARCH: arm64
          - GOOS: darwin
            GOARCH: arm64
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: |
          BINARY=contest
          if [[ $GOOS == "windows" ]];
          then
            BINARY=contest.exe
          fi
          go build -o $BINARY;
          tar -cvzf contest-${GOOS}-${GOARCH}.tar.gz $BINARY
      - uses: actions/upload-artifact@v3
        with:
          name: contest-${GOOS}-${GOARCH}.tar.gz
          path: contest-${GOOS}-${GOARCH}.tar.gz
